export enum inventoryTypes {
    FETCH_INVENTORY_REQUEST = "FETCH_INVENTORY_REQUEST",
    FETCH_INVENTORY_SUCCESS = "FETCH_INVENTORY_SUCCESS",
    FETCH_INVENTORY_FAILURE = "FETCH_INVENTORY_FAILURE",
    UPDATE_INVENTORY = "UPDATE_INVENTORY",
    REMOVE_INVENTORY = "REMOVE_INVENTORY"
  }
  